language: r
sudo: false
cache: packages
warnings_are_errors: false
addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:opencpu/imagemagick
    packages:
    - libmagick++-dev
env:
  matrix:
    secure: v0Cq4HjVG7We9z5x2rZ8h+2mV9Z9fHHHTmwfROREtCV7NuQ8baJ5n1dm7y+yR7mzLvdNdeoLs+nlr6+Jx04rOmoCXd5sk8S/K7+5g1kVICzm0dVyNZqaDgLhu2lRraU549dRAG7IfAnJCmU8Fi/0XRFILy/h6oBDyP6V+hPEkwB3ViZGhNChkoOjOrhPEgit0YMX9bMXFo8FwPeNVjgunAsg3HXKkWnXy7Tut/j5T8wLoxaN1m/UOHbEvsnJC9ncGhkeASsVRrb3Q7YMQv0qlXk7DwebFsu3W0AnKv7F9QbennrnRoSXXiJa1K9fgt00gl5VOZGotG10pCyCdUC1DFc0C/CLREZxXQYTqgmfjsX27I7LGUxWRKwPlhHs/9AM6x0bkpYDlSqZABw5A/p9QxyCmf5EPQrG+SFiR7RU0Tj66CJ91ZplFVE//c+sDpee6CSs2+CTMwoVountLhLfNLt/rm7uHb1IvtHvZAvBk+hyx2lgdmIVXvCESDowdcMVotLdbPLaN/gi09FYmsT064HTehfTxyMf+yTVr2HbvrD56j7OIDiSxwBV0klGrQnYYHmwXzBamfYiGHBIOUS0nfYySSM5n7ZfSfjf3mBLL3ZgtBo3Dyma2lryUM9doYcltp+mNcwPOPXzduUUdCe3qwaT4vIwdgBcOvSZ+lJ7TW4=

